Feature/positioning
7ninjas/scss-mixins pull request #15
Opened 2018-01-09 11:34 UTC by CodeMeNatalie

2018-01-09 11:57 UTC, ArekRado requested changes

2018-01-09 11:57 UTC, ArekRado commented on docs/positioning.md
> +_Bootstrap helper which helps _
please add better description ;)

2018-01-09 12:03 UTC, ArekRado approved these changes

2018-01-10 12:14 UTC, ArekRado requested changes

2018-01-10 12:14 UTC, ArekRado commented on docs/positioning.md
> +    @include z('header');
z-index

2018-01-10 12:45 UTC, JSerhii requested changes

2018-01-10 12:45 UTC, Serhii-Hulko commented on docs/positioning.md
> +_Bootstrap mixin which helps with wrapping containers_
Bootstrap helper. Used on a container of which all the children are floating. If you would not use this, the container would not get any height (except in IE)

2018-01-10 12:45 UTC, Serhii-Hulko commented on docs/positioning.md
> +_Mixin which helps with positioning element with content, display and position properties._
...positioning speudo elements

2018-01-10 12:45 UTC, Serhii-Hulko commented on docs/positioning.md
> +}
```scss
.exampleClass {
   &:before {
       @include pseudo(block, absolute);
       ...
    }
   &:after {
       @include pseudo();
       ...
   }
}
```

2018-01-10 12:45 UTC, Serhii-Hulko commented on docs/positioning.md
> +    @include fixed();
```scss
...
@include fixed(left 50% bottom 150px);
...
```

2018-01-10 12:45 UTC, Serhii-Hulko commented on docs/positioning.md
> +    @include absolute();
```scss
...
@include absolute(top 0 left 0 bottom 0);
...
```

2018-01-10 12:45 UTC, Serhii-Hulko commented on src/_positioning.scss
> +@mixin pseudo($display: block, $pos: absolute, $content: '') {
I think we can remove prop `position` from this mixin and use mixins `absolute` or `relative` for pseudo elements

2018-01-10 13:54 UTC, JSerhii approved these changes

2018-01-10 13:58 UTC, ArekRado approved these changes

2018-01-10 13:59 UTC, merged