best practices document
7ninjas/scss-mixins pull request #54
Opened 2018-01-15 14:02 UTC by CodeMeNatalie

Issue: #27

2018-01-23 12:46 UTC, ArekRado requested changes

2018-01-23 12:46 UTC, ArekRado commented on BEST_PRACTICES.md
> +     @include pl(2);
it should be real tab

2018-01-23 12:46 UTC, ArekRado commented on BEST_PRACTICES.md
> +Good practice:
plz add more examples, how to style external react-components which don't use css-modules: (it's good practice to wrap each `global` by normal classes)

```scss
.cell {
  @include flex($direction: column);
  @include p(0.5, 1);
  @include m(0.5, 0);

  :global {
    .Select.is-focused > .Select-control,
    .Select-control {
      border: none;
      border-bottom: 1px solid $color-gray-darker;
      background-color: transparent;
      border-radius: 0;
    }
  }
}
```

2018-01-23 12:46 UTC, ArekRado commented on BEST_PRACTICES.md
> +Good practice:
how to style another react components which use css-modules, is it possible to change theirs styles?

2018-02-09 13:17 UTC, JSerhii approved these changes

2018-02-09 13:17 UTC, Serhii-Hulko commented on BEST_PRACTICES.md
> +.container {
```css
.container {
   &.active {
     ...
   }
}
```

2018-02-09 13:17 UTC, Serhii-Hulko commented on BEST_PRACTICES.md
> +  .button {
```
.button {
   &.hovered {
     ...
   }
}
```

2018-02-09 13:17 UTC, Serhii-Hulko commented on BEST_PRACTICES.md
> +  @include p(2, 2, 2, 2);
add another example
```
@include p(2, 3, 2, 4);
```

or 

```
@include p(2);
```

2018-02-09 13:58 UTC, ArekRado approved these changes

2018-02-09 13:59 UTC, merged